[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'pulsar-2'
rpc_addr = 'https://rpc.pulsar.scrttestnet.com:443'
grpc_addr = 'http://grpcbin.pulsar.scrttestnet.com:9099'
websocket_addr = 'wss://rpc.pulsar.scrttestnet.com:443/websocket'
rpc_timeout = '15s'
account_prefix = 'secret'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0125, denom = 'uscrt' }
gas_multiplier = 1.1
default_gas = 1000000
max_gas = 10000000
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '2', denominator = '3' }

# [chains.packet_filter]
# policy = 'allow'
# list = [
#   ['ica*', '*'],
#   ['transfer', 'channel-0'],
# ]

[[chains]]
id = 'uni-6'
rpc_addr = 'https://rpc.uni.juno.deuslabs.fi:443'
grpc_addr = 'http://juno-testnet-grpc.polkachu.com:12690'
websocket_addr = 'wss://rpc.uni.juno.deuslabs.fi:443/websocket'
rpc_timeout = '15s'
account_prefix = 'juno'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ujunox' }
gas_multiplier = 1.1
default_gas = 1000000
max_gas = 10000000
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

# [chains.packet_filter]
# policy = 'allow'
# list = [
#   ['ica*', '*'],
#   ['transfer', 'channel-0'],
# ]
